[tool.ruff]
target-version = "py312"
line-length = 120

# ВКЛЮЧАЕМ только безопасные правила
select = [
    "F",   # pyflakes (ошибки, неиспользуемые импорты)
]

# НЕ трогаем стиль
ignore = []

# Исключаем папки
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "venv",
]
